# Generated by Django 2.2.3 on 2021-03-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(choices=[('0', 'Rojo'), ('1', 'Amarillo'), ('2', 'Verde'), ('3', 'Azul'), ('4', 'Negro')], max_length=1)),
                ('deposito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuto_app.Deposito')),
            ],
        ),
    ]
